### PR TITLE
Adding enter in normal mode to save file

### PR DESCRIPTION
**Pull request by sentientmonkey**
Signed-off-by: Adam Cobb <adamcob@pivotal.io>

### CODE REVIEW

**Comment by slackersoft** [comment]
My inclination is "no", but mostly because I don't understand the use case. I'm happy to be convinced otherwise.

**Comment by sgravrock** [comment]
I could see this causing data loss in the hands of a user who knows that you have to type :w to save and is unaware of the customization. As an organization that prioritizes welcoming new people, we should avoid customizations that impose an office-specific learning curve on people who already know vim.

**Comment by sentientmonkey** [comment]
Good feedback! This was a suggestion from Adam while we were pairing today (I think it comes from Luan’s config). The idea is that in normal mode the file saves on “enter”, which makes it easier and faster for frequent saves (which with go reformats and syntax checks the file). I have a fair amount of muscle memory with :w but this may help others? I’m also totally ok with not accepting the PR and making it a project-specific (team-level) setting.

**Comment by adamos486** [comment]
My use case was my muscle memory coming into VIM as a main editor was a rote memorized `:wq` used in mainly git scenarios. I found myself accidentally quitting my files, something I'm repatterning now. Happy to just leave this as my own machine, though.

**Comment by kejadlen** [comment]
+feedback from @alidaka:

> Some slight unease with overriding common keys to do something completely different than the base config. Not that enter in normal mode is super useful, but like @sgravrock mentioned, it would be surprising to beginners. Plugins/new functionality are safe, or changing nonsense actions people wouldn't have expectations for (`ctrl+[`, `j+k,`, stuff like that). But if soloing I would be pretty indifferent. In my mild opinion :shrug:

Closing since consensus leans towards this being somewhat unexpected behavior for people familiar w/vim.

I don't think it's unreasonable to add a shortcut for saving in insert mode, though...

**Pull request closed without merging**
